apiVersion: v1
baseDomain: lab
compute: 
- hyperthreading: Enabled 
  name: worker
  replicas: 0 
controlPlane: 
  hyperthreading: Enabled 
  name: master
  replicas: 3 
metadata:
  name: ocp 
networking:
  clusterNetwork:
  - cidr: 10.24.0.0/16
    hostPrefix: 23 
  networkType: OVNKubernetes
  serviceNetwork: 
  - 10.34.0.0/16
platform:
  none: {} 
fips: false 
pullSecret: ''
sshKey: '' 
